name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#env:
#  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
#  DOTNET_CLI_TELEMETRY_OPTOUT: true

  #PROJECT_NAME: FluentValidationLister.Filter
  
  #TESTS_NAME: FluentValidationLister.Tests

  #GITHUB_FEED: https://nuget.pkg.github.com/scandal-uk/

  #GITHUB_USER: scandal-uk

  #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore project
      run: dotnet restore FluentValidationLister.Filter/FluentValidationLister.Filter.csproj

    - name: Restore tests
      run: dotnet restore FluentValidationLister.Tests/FluentValidationLister.Tests.csproj

    - name: Build project
      run: dotnet build FluentValidationLister.Filter/FluentValidationLister.Filter.csproj --no-restore --configuration Release

    - name: Build tests
      run: dotnet build FluentValidationLister.Tests/FluentValidationLister.Tests.csproj --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-restore --no-build

#   - name: Pack project
#     run: dotnet pack -v normal --no-build --no-restore --include-symbols --include-source -p:PackageVersion=$GITHUB_RUN_ID FluentValidationLister.Filter/FluentValidationLister.Filter.*proj

#   - name: Upload artifact
#     uses: actions/upload-artifact@v2
#     with:
#       name: nupkg
#       path: ./FluentValidationLister.Filter/bin/Release/*.nupkg

# prerelease:
#   needs: build
#   if: github.ref == 'refs/heads/develop'
#   runs-on: ubuntu-latest

#   steps:
#   - name: Download artifact
#     uses: actions/download-artifact@v1
#     with:
#       name: nupkg

    # Push the current develop branch as prerelease package(s)
#   - name: Push to GitHub feed
#     run: |
#       for f in ./nupkg/*.nupkg
#       do
#         curl -vX PUT -u "scandal-uk:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/scandal-uk/
#       done
