name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies for filter
      run: dotnet restore FluentValidationLister.Filter/FluentValidationLister.Filter.csproj

    - name: Build filter
      run: dotnet build FluentValidationLister.Filter/FluentValidationLister.Filter.csproj --configuration Release --no-restore

    - name: Restore dependencies for tests
      run: dotnet restore FluentValidationLister.Tests/FluentValidationLister.Tests.csproj

    - name: Build tests
      run: dotnet build FluentValidationLister.Tests/FluentValidationLister.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --no-build --verbosity normal
