deploy:
  needs: build
  if: github.ref == 'refs/heads/main'
  runs-on: ubuntu-latest

  permissions:
    contents: write
    id-token: write

  steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Set package version from .csproj
      id: set_version
      run: |
        version=$(grep -oPm1 "(?<=<Version>)[^<]+" $PROJECT_NAME/$PROJECT_NAME.csproj)
        echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV

    - name: Pack the project
      run: dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=$PACKAGE_VERSION $PROJECT_NAME/$PROJECT_NAME.csproj

    - name: NuGet login
      id: nuget-login
      uses: NuGet/login@v1
      with:
        user: Scandal-UK

    - name: Push build to NuGet including symbols
      run: >
        dotnet nuget push
        ./${{ env.PROJECT_NAME }}/bin/Release/*.nupkg
        --skip-duplicate
        --source $NUGET_FEED
        --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }}

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.PACKAGE_VERSION }}
        name: v${{ env.PACKAGE_VERSION }}
        generate_release_notes: true
