name: Build and Test

on: [push, pull_request]
  branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies for filter
      run: dotnet restore FluentValidationLister.Filter/FluentValidationLister.Filter.csproj

    - name: Restore dependencies for test
      run: dotnet restore FluentValidationLister.Tests/FluentValidationLister.Tests.csproj

    - name: Build filter
      run: dotnet build FluentValidationLister.Filter/FluentValidationLister.Filter.csproj --no-restore

    - name: Build tests
      run: dotnet build FluentValidationLister.Tests/FluentValidationLister.Tests.csproj --no-restore

    - name: Test
      run: dotnet test --no-restore --no-build
